### ISSUE TITLE
Example for creating streams in bulk

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-sandbox#4]
Requested by Dennison from Tally. See [Notion](https://www.notion.so/sablier/Write-a-frontend-example-for-how-to-create-streams-in-bulk-f08fb2347df2486c8f01c3c1e93a4b50) for more details.

- Has to use Ethers
- Use the simple [`Batch`](https://github.com/sablier-labs/v2-periphery/blob/0004fd2e61e032df3d895045ec414ecb212ddcc8/src/SablierV2Batch.sol) contract
- Use the simple ERC-20 allowance system (not `Permit2`)

**Comment by PaulRBerg** [comment]
Will you be able to write these examples this week, @razgraf, @gavriliumircea?

I would not want to lose Tally.

Side note - I know that these integrations can be hit-and-miss, as it happened with Pulley, but we need to try to do them at any rate. At a minimum we are left with some example code that can be reused later.

**Comment by razgraf** [comment]
Yes, I will try to have everything ready this week. Allow me one more day to finish reviewing and improving a PR and I will switch context after that to configure the dedicated sandbox.

**Comment by PaulRBerg** [comment]
I deployed Batch using commit [f8a14ed](https://github.com/sablier-labs/v2-periphery/tree/f8a14edb11cac2e0467f543d0a706dcc7d0010f6) on Arbitrum and Ethereum (the only chains Tally is interested in):

- [arb:0xc953E29b8deDD43c4722FD49895f2CA8D284f308](https://arbiscan.io/address/0xc953e29b8dedd43c4722fd49895f2ca8d284f308)
- [eth:0x62D0d5BF3151Fdf6C8d9Be6aad2747DB6c5239A9](https://etherscan.io/address/0x62d0d5bf3151fdf6c8d9be6aad2747db6c5239a9)

**Comment by razgraf** [comment]
Done, see the [`feat/batch-v2.0`](https://github.com/sablier-labs/v2-sandbox/tree/feat/batch-v2.0) branch.

**Comment by PaulRBerg** [comment]
Thanks but why not on `main`?
